name: 'Setup mold'
description: 'Install mold as the default linker'
inputs:
  mold-version:
    description: 'The mold version to download'
    default: '1.10.1'
  make-default:
    description: 'Make mold the default linker'
    default: true
runs:
  using: composite
  steps:
    - run: |
        echo "mold ${{ inputs.mold-version }}"
        curl -L --retry 10 --silent --show-error https://github.com/rui314/mold/releases/download/v${{ inputs.mold-version }}/mold-${{ inputs.mold-version }}-$(uname -m)-linux.tar.gz | sudo tar -C /usr/local --strip-components=1 -xzf -
        test ${{ inputs.make-default }} = true -a "$(realpath /usr/bin/ld)" != /usr/local/bin/mold && sudo ln -sf /usr/local/bin/mold "$(realpath /usr/bin/ld)"; true
      shell: bash
      if: runner.os == 'linux'
